name: Duplicate Repository and Send Invite

on:
  workflow_dispatch:
    inputs:
      newRepoName:
        description: 'Name for the duplicated repository'
        required: true
      inviteeUsername:
        description: 'GitHub Username to send invite'
        required: true

jobs:
  duplicate_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create new GitHub repository
        run: |
          RESPONSE=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user/repos \
          -d '{"name":"${{ github.event.inputs.newRepoName }}", "private": true}')
          echo "$RESPONSE" > repo_response.json

      - name: Set up Git and push to new repository
        run: |
          NEW_REPO_GIT_URL=$(jq -r .ssh_url repo_response.json)
          git init
          git remote add origin $NEW_REPO_GIT_URL
          git add .
          git commit -m "Duplicate original repository"
          git branch -M main
          git push -u origin main

      - name: Invite user to the new repository
        run: |
          REPO_FULL_NAME=$(jq -r .full_name repo_response.json)
          curl -s -X PUT \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_FULL_NAME/collaborators/${{ github.event.inputs.inviteeUsername }} \
          -d '{"permission": "push"}'
