name: Create Private Fork and Invite

on:
  workflow_dispatch:
    inputs:
      forkName:
        description: 'Name for the new fork repository'
        required: true
      candidateUsername:
        description: 'Candidate GitHub Username'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Create Fork
        run: |
          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/forks\
            -d '{"name":"${{ github.event.inputs.forkName }}, "private": true}'\)
          echo "Fork creation response: $RESPONSE"

      - name: Invite Candidate
        run: |
          USER_ID=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
          https://api.github.com/users/${{ github.event.inputs.candidateUsername }} | jq .id)
          INVITE_RESPONSE=$(curl -X PUT -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -d '{"permission": "push"}' \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.forkName }}/collaborators/$USER_ID)
          echo "Invitation response: $INVITE_RESPONSE"
